// <auto-generated />
using System;
using Bintangku.WebApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Bintangku.WebApi.Data.Migrations
{
    [DbContext(typeof(ApplicationDataContext))]
    [Migration("20210515151535_InitialMigrations")]
    partial class InitialMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.AppUserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.DataAnak", b =>
                {
                    b.Property<int>("DataAnakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Alamat")
                        .HasColumnType("text");

                    b.Property<string>("ImagePath")
                        .HasColumnType("text");

                    b.Property<string>("JenisKelamin")
                        .HasColumnType("text");

                    b.Property<byte?>("JumlahSaudara")
                        .HasColumnType("smallint");

                    b.Property<string>("Kontak")
                        .HasColumnType("text");

                    b.Property<int?>("NIK")
                        .HasColumnType("integer");

                    b.Property<int>("NakesUserId")
                        .HasColumnType("integer");

                    b.Property<string>("NamaLengkap")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TanggalLahirAnak")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UmurAnak")
                        .HasColumnType("integer");

                    b.HasKey("DataAnakId");

                    b.HasIndex("NakesUserId");

                    b.ToTable("DataAnaks");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiAnak", b =>
                {
                    b.Property<int>("ImunisasiAnakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("DataAnakId")
                        .HasColumnType("integer");

                    b.HasKey("ImunisasiAnakId");

                    b.HasIndex("DataAnakId")
                        .IsUnique();

                    b.ToTable("ImunisasiAnaks");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiBCG", b =>
                {
                    b.Property<int>("ImunisasiBCGId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte?>("Bulan1")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan15")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan2")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan24")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan4")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan9")
                        .HasColumnType("smallint");

                    b.Property<int>("ImunisasiAnakId")
                        .HasColumnType("integer");

                    b.Property<byte?>("Lahir")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun10")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun7")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun8")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun9")
                        .HasColumnType("smallint");

                    b.HasKey("ImunisasiBCGId");

                    b.HasIndex("ImunisasiAnakId")
                        .IsUnique();

                    b.ToTable("ImunisasiBCGs");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiCampak", b =>
                {
                    b.Property<int>("ImunisasiCampakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte?>("Bulan1")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan15")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan2")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan24")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan4")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan9")
                        .HasColumnType("smallint");

                    b.Property<int>("ImunisasiAnakId")
                        .HasColumnType("integer");

                    b.Property<byte?>("Lahir")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun10")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun7")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun8")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun9")
                        .HasColumnType("smallint");

                    b.HasKey("ImunisasiCampakId");

                    b.HasIndex("ImunisasiAnakId")
                        .IsUnique();

                    b.ToTable("ImunisasiCampaks");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiDTP", b =>
                {
                    b.Property<int>("ImunisasiDTPId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte?>("Bulan1")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan15")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan2")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan24")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan4")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan9")
                        .HasColumnType("smallint");

                    b.Property<int>("ImunisasiAnakId")
                        .HasColumnType("integer");

                    b.Property<byte?>("Lahir")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun10")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun7")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun8")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun9")
                        .HasColumnType("smallint");

                    b.HasKey("ImunisasiDTPId");

                    b.HasIndex("ImunisasiAnakId")
                        .IsUnique();

                    b.ToTable("ImunisasiDTPs");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiDengue", b =>
                {
                    b.Property<int>("ImunisasiDengueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte?>("Bulan1")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan15")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan2")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan24")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan4")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan9")
                        .HasColumnType("smallint");

                    b.Property<int>("ImunisasiAnakId")
                        .HasColumnType("integer");

                    b.Property<byte?>("Lahir")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun10")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun7")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun8")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun9")
                        .HasColumnType("smallint");

                    b.HasKey("ImunisasiDengueId");

                    b.HasIndex("ImunisasiAnakId")
                        .IsUnique();

                    b.ToTable("ImunisasiDengues");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiHPV", b =>
                {
                    b.Property<int>("ImunisasiHpvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte?>("Bulan1")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan15")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan2")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan24")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan4")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan9")
                        .HasColumnType("smallint");

                    b.Property<int>("ImunisasiAnakId")
                        .HasColumnType("integer");

                    b.Property<byte?>("Lahir")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun10")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun7")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun8")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun9")
                        .HasColumnType("smallint");

                    b.HasKey("ImunisasiHpvId");

                    b.HasIndex("ImunisasiAnakId")
                        .IsUnique();

                    b.ToTable("ImunisasiHPVs");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiHepatitisA", b =>
                {
                    b.Property<int>("ImunisasiHepatitisAId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte?>("Bulan1")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan15")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan2")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan24")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan4")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan9")
                        .HasColumnType("smallint");

                    b.Property<int>("ImunisasiAnakId")
                        .HasColumnType("integer");

                    b.Property<byte?>("Lahir")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun10")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun7")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun8")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun9")
                        .HasColumnType("smallint");

                    b.HasKey("ImunisasiHepatitisAId");

                    b.HasIndex("ImunisasiAnakId")
                        .IsUnique();

                    b.ToTable("ImunisasiHepatitisAs");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiHepatitisB", b =>
                {
                    b.Property<int>("ImunisasiHepatitisBId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte?>("Bulan1")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan15")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan2")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan24")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan4")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan9")
                        .HasColumnType("smallint");

                    b.Property<int>("ImunisasiAnakId")
                        .HasColumnType("integer");

                    b.Property<byte?>("Lahir")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun10")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun7")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun8")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun9")
                        .HasColumnType("smallint");

                    b.HasKey("ImunisasiHepatitisBId");

                    b.HasIndex("ImunisasiAnakId")
                        .IsUnique();

                    b.ToTable("ImunisasiHepatitisBs");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiHib", b =>
                {
                    b.Property<int>("ImunisasiHibId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte?>("Bulan1")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan15")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan2")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan24")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan4")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan9")
                        .HasColumnType("smallint");

                    b.Property<int>("ImunisasiAnakId")
                        .HasColumnType("integer");

                    b.Property<byte?>("Lahir")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun10")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun7")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun8")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun9")
                        .HasColumnType("smallint");

                    b.HasKey("ImunisasiHibId");

                    b.HasIndex("ImunisasiAnakId")
                        .IsUnique();

                    b.ToTable("ImunisasiHibs");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiInfluenza", b =>
                {
                    b.Property<int>("ImunisasiInfluenzaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte?>("Bulan1")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan15")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan2")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan24")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan4")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan9")
                        .HasColumnType("smallint");

                    b.Property<int>("ImunisasiAnakId")
                        .HasColumnType("integer");

                    b.Property<byte?>("Lahir")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun10")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun7")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun8")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun9")
                        .HasColumnType("smallint");

                    b.HasKey("ImunisasiInfluenzaId");

                    b.HasIndex("ImunisasiAnakId")
                        .IsUnique();

                    b.ToTable("ImunisasiInfluenzas");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiJapaneseEncephalitis", b =>
                {
                    b.Property<int>("ImunisasiJapaneseEncephalitisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte?>("Bulan1")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan15")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan2")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan24")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan4")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan9")
                        .HasColumnType("smallint");

                    b.Property<int>("ImunisasiAnakId")
                        .HasColumnType("integer");

                    b.Property<byte?>("Lahir")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun10")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun7")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun8")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun9")
                        .HasColumnType("smallint");

                    b.HasKey("ImunisasiJapaneseEncephalitisId");

                    b.HasIndex("ImunisasiAnakId")
                        .IsUnique();

                    b.ToTable("ImunisasiJapaneseEncephalitis");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiMMR", b =>
                {
                    b.Property<int>("ImunisasiMMRId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte?>("Bulan1")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan15")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan2")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan24")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan4")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan9")
                        .HasColumnType("smallint");

                    b.Property<int>("ImunisasiAnakId")
                        .HasColumnType("integer");

                    b.Property<byte?>("Lahir")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun10")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun7")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun8")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun9")
                        .HasColumnType("smallint");

                    b.HasKey("ImunisasiMMRId");

                    b.HasIndex("ImunisasiAnakId")
                        .IsUnique();

                    b.ToTable("ImunisasiMMRs");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiPCV", b =>
                {
                    b.Property<int>("ImunisasiPCVId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte?>("Bulan1")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan15")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan2")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan24")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan4")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan9")
                        .HasColumnType("smallint");

                    b.Property<int>("ImunisasiAnakId")
                        .HasColumnType("integer");

                    b.Property<byte?>("Lahir")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun10")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun7")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun8")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun9")
                        .HasColumnType("smallint");

                    b.HasKey("ImunisasiPCVId");

                    b.HasIndex("ImunisasiAnakId")
                        .IsUnique();

                    b.ToTable("ImunisasiPCVs");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiPolio", b =>
                {
                    b.Property<int>("ImunisasiPolioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte?>("Bulan1")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan15")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan2")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan24")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan4")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan9")
                        .HasColumnType("smallint");

                    b.Property<int>("ImunisasiAnakId")
                        .HasColumnType("integer");

                    b.Property<byte?>("Lahir")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun10")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun7")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun8")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun9")
                        .HasColumnType("smallint");

                    b.HasKey("ImunisasiPolioId");

                    b.HasIndex("ImunisasiAnakId")
                        .IsUnique();

                    b.ToTable("ImunisasiPolios");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiRotavirus", b =>
                {
                    b.Property<int>("ImunisasiRotavirusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte?>("Bulan1")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan15")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan2")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan24")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan4")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan9")
                        .HasColumnType("smallint");

                    b.Property<int>("ImunisasiAnakId")
                        .HasColumnType("integer");

                    b.Property<byte?>("Lahir")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun10")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun7")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun8")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun9")
                        .HasColumnType("smallint");

                    b.HasKey("ImunisasiRotavirusId");

                    b.HasIndex("ImunisasiAnakId")
                        .IsUnique();

                    b.ToTable("ImunisasiRotaviruses");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiTifoid", b =>
                {
                    b.Property<int>("ImunisasiTifoidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte?>("Bulan1")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan15")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan2")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan24")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan4")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan9")
                        .HasColumnType("smallint");

                    b.Property<int>("ImunisasiAnakId")
                        .HasColumnType("integer");

                    b.Property<byte?>("Lahir")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun10")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun7")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun8")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun9")
                        .HasColumnType("smallint");

                    b.HasKey("ImunisasiTifoidId");

                    b.HasIndex("ImunisasiAnakId")
                        .IsUnique();

                    b.ToTable("ImunisasiTifoids");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiVarisela", b =>
                {
                    b.Property<int>("ImunisasiVariselaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte?>("Bulan1")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan15")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan2")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan24")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan4")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Bulan9")
                        .HasColumnType("smallint");

                    b.Property<int>("ImunisasiAnakId")
                        .HasColumnType("integer");

                    b.Property<byte?>("Lahir")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun10")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun12")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun18")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun3")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun5")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun6")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun7")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun8")
                        .HasColumnType("smallint");

                    b.Property<byte?>("Tahun9")
                        .HasColumnType("smallint");

                    b.HasKey("ImunisasiVariselaId");

                    b.HasIndex("ImunisasiAnakId")
                        .IsUnique();

                    b.ToTable("ImunisasiVariselas");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.KesehatanAnak", b =>
                {
                    b.Property<int>("KesehatanAnakId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("DataAnakId")
                        .HasColumnType("integer");

                    b.Property<int>("PemeriksaanBeratBadan")
                        .HasColumnType("integer");

                    b.Property<int>("PemeriksaanTinggiBadan")
                        .HasColumnType("integer");

                    b.HasKey("KesehatanAnakId");

                    b.HasIndex("DataAnakId")
                        .IsUnique();

                    b.ToTable("KesehatanAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.NakesUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("NoStrTenagaKesehatan")
                        .HasColumnType("bigint");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("TempatPelayanan")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Pemeriksaan.PemeriksaanDayaDengar", b =>
                {
                    b.Property<int>("PemeriksaanDayaDengarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Interpretasi")
                        .HasColumnType("text");

                    b.Property<string>("Intervensi")
                        .HasColumnType("text");

                    b.Property<int>("KesehatanAnakId")
                        .HasColumnType("integer");

                    b.HasKey("PemeriksaanDayaDengarId");

                    b.HasIndex("KesehatanAnakId");

                    b.ToTable("PemeriksaanDayaDengars");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Pemeriksaan.PemeriksaanDayaLihat", b =>
                {
                    b.Property<int>("PemeriksaanDayaLihatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Interpretasi")
                        .HasColumnType("text");

                    b.Property<string>("Intervensi")
                        .HasColumnType("text");

                    b.Property<int>("KesehatanAnakId")
                        .HasColumnType("integer");

                    b.Property<int>("MataKanan")
                        .HasColumnType("integer");

                    b.Property<int>("MataKiri")
                        .HasColumnType("integer");

                    b.HasKey("PemeriksaanDayaLihatId");

                    b.HasIndex("KesehatanAnakId");

                    b.ToTable("PemeriksaanDayaLihats");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Pemeriksaan.PemeriksaanGpph", b =>
                {
                    b.Property<int>("PemeriksaanGpphId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Interpretasi")
                        .HasColumnType("text");

                    b.Property<string>("Intervensi")
                        .HasColumnType("text");

                    b.Property<int>("KesehatanAnakId")
                        .HasColumnType("integer");

                    b.Property<byte>("Point")
                        .HasColumnType("smallint");

                    b.Property<byte>("Question1")
                        .HasColumnType("smallint");

                    b.Property<byte>("Question10")
                        .HasColumnType("smallint");

                    b.Property<byte>("Question2")
                        .HasColumnType("smallint");

                    b.Property<byte>("Question3")
                        .HasColumnType("smallint");

                    b.Property<byte>("Question4")
                        .HasColumnType("smallint");

                    b.Property<byte>("Question5")
                        .HasColumnType("smallint");

                    b.Property<byte>("Question6")
                        .HasColumnType("smallint");

                    b.Property<byte>("Question7")
                        .HasColumnType("smallint");

                    b.Property<byte>("Question8")
                        .HasColumnType("smallint");

                    b.Property<byte>("Question9")
                        .HasColumnType("smallint");

                    b.HasKey("PemeriksaanGpphId");

                    b.HasIndex("KesehatanAnakId");

                    b.ToTable("PemeriksaanKesehatanGPPH");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Pemeriksaan.PemeriksaanKmpe", b =>
                {
                    b.Property<int>("PemeriksaanKmpeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Interpretasi")
                        .HasColumnType("text");

                    b.Property<string>("Intervensi")
                        .HasColumnType("text");

                    b.Property<byte>("JumlahYa")
                        .HasColumnType("smallint");

                    b.Property<int>("KesehatanAnakId")
                        .HasColumnType("integer");

                    b.Property<bool>("Question1")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question10")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question11")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question12")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question13")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question14")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question2")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question3")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question4")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question5")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question6")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question7")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question8")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question9")
                        .HasColumnType("boolean");

                    b.HasKey("PemeriksaanKmpeId");

                    b.HasIndex("KesehatanAnakId");

                    b.ToTable("PemeriksaanKesehatanKMPE");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Pemeriksaan.PemeriksaanKpsp", b =>
                {
                    b.Property<int>("PemeriksaanKpspId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Interpretasi")
                        .HasColumnType("text");

                    b.Property<int>("JumlahYa")
                        .HasColumnType("integer");

                    b.Property<int>("KesehatanAnakId")
                        .HasColumnType("integer");

                    b.Property<string>("Tindakan")
                        .HasColumnType("text");

                    b.HasKey("PemeriksaanKpspId");

                    b.HasIndex("KesehatanAnakId");

                    b.ToTable("PemeriksaanKpsps");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Pemeriksaan.PemeriksaanLingkarKepala", b =>
                {
                    b.Property<int>("PemeriksaanLingkarKepalaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("KesehatanAnakId")
                        .HasColumnType("integer");

                    b.Property<string>("Klasifikasi")
                        .HasColumnType("text");

                    b.Property<int>("Kurva")
                        .HasColumnType("integer");

                    b.Property<int>("LingkarKepala")
                        .HasColumnType("integer");

                    b.Property<string>("Tindakan")
                        .HasColumnType("text");

                    b.HasKey("PemeriksaanLingkarKepalaId");

                    b.HasIndex("KesehatanAnakId");

                    b.ToTable("PemeriksaanLingkarKepalas");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Pemeriksaan.PemeriksaanMchat", b =>
                {
                    b.Property<int>("PemeriksaanMchatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Interpretasi")
                        .HasColumnType("text");

                    b.Property<string>("Intervensi")
                        .HasColumnType("text");

                    b.Property<int>("KesehatanAnakId")
                        .HasColumnType("integer");

                    b.Property<bool>("Question1")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question10")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question11")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question12")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question13")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question14")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question15")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question16")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question17")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question18")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question19")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question2")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question20")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question21")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question22")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question23")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question3")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question4")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question5")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question6")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question7")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question8")
                        .HasColumnType("boolean");

                    b.Property<bool>("Question9")
                        .HasColumnType("boolean");

                    b.Property<int>("TotalCriticalQuestionNo")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCriticalQuestionYes")
                        .HasColumnType("integer");

                    b.Property<int>("TotalQuestionNo")
                        .HasColumnType("integer");

                    b.Property<int>("TotalQuestionYes")
                        .HasColumnType("integer");

                    b.HasKey("PemeriksaanMchatId");

                    b.HasIndex("KesehatanAnakId");

                    b.ToTable("PemeriksaanKesehatanM-CHAT");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Pemeriksaan.PemeriksaanStatusGiziBbTb", b =>
                {
                    b.Property<int>("PemeriksaanStatusGiziBbTbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("BeratBadan")
                        .HasColumnType("integer");

                    b.Property<int>("KesehatanAnakId")
                        .HasColumnType("integer");

                    b.Property<string>("StatusGizi")
                        .HasColumnType("text");

                    b.Property<string>("Tindakan")
                        .HasColumnType("text");

                    b.Property<int>("TinggiBadan")
                        .HasColumnType("integer");

                    b.Property<int>("ZCode")
                        .HasColumnType("integer");

                    b.HasKey("PemeriksaanStatusGiziBbTbId");

                    b.HasIndex("KesehatanAnakId");

                    b.ToTable("PemeriksaanStatusGiziBbTbs");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Pemeriksaan.PemeriksaanStatusGiziImtU", b =>
                {
                    b.Property<int>("PemeriksaanStatusGiziImtUId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("BeratBadan")
                        .HasColumnType("integer");

                    b.Property<int>("IMT")
                        .HasColumnType("integer");

                    b.Property<int>("KesehatanAnakId")
                        .HasColumnType("integer");

                    b.Property<string>("StatusGizi")
                        .HasColumnType("text");

                    b.Property<string>("Tindakan")
                        .HasColumnType("text");

                    b.Property<int>("TinggiBadan")
                        .HasColumnType("integer");

                    b.Property<int>("Umur")
                        .HasColumnType("integer");

                    b.Property<int>("ZCode")
                        .HasColumnType("integer");

                    b.HasKey("PemeriksaanStatusGiziImtUId");

                    b.HasIndex("KesehatanAnakId");

                    b.ToTable("PemeriksaanStatusGiziImtUs");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Pemeriksaan.PemeriksaanStatusGiziIpTb", b =>
                {
                    b.Property<int>("PemeriksaanStatusGiziIpTbId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("IndeksPanjang")
                        .HasColumnType("integer");

                    b.Property<int>("KesehatanAnakId")
                        .HasColumnType("integer");

                    b.Property<string>("StatusGizi")
                        .HasColumnType("text");

                    b.Property<string>("Tindakan")
                        .HasColumnType("text");

                    b.Property<int>("TinggiBadan")
                        .HasColumnType("integer");

                    b.Property<int>("ZCode")
                        .HasColumnType("integer");

                    b.HasKey("PemeriksaanStatusGiziIpTbId");

                    b.HasIndex("KesehatanAnakId");

                    b.ToTable("PemeriksaanStatusGiziIpTbs");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<bool>("IsMain")
                        .HasColumnType("boolean");

                    b.Property<int>("NakesUserId")
                        .HasColumnType("integer");

                    b.Property<string>("PublicId")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NakesUserId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.RiwayatKelahiran", b =>
                {
                    b.Property<int>("RiwayatKelahiranId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<int>("ApgarScore")
                        .HasColumnType("integer");

                    b.Property<byte>("BeratBadan")
                        .HasColumnType("smallint");

                    b.Property<int>("DataAnakId")
                        .HasColumnType("integer");

                    b.Property<string>("KelahiranDibantuOleh")
                        .HasColumnType("text");

                    b.Property<string>("LainLain")
                        .HasColumnType("text");

                    b.Property<int>("PanjangLahir")
                        .HasColumnType("integer");

                    b.HasKey("RiwayatKelahiranId");

                    b.HasIndex("DataAnakId")
                        .IsUnique();

                    b.ToTable("RiwayatKelahiran");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.RiwayatOrangTua", b =>
                {
                    b.Property<int>("RiwayatOrangTuaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<byte>("AnggotaRumahTangga")
                        .HasColumnType("smallint");

                    b.Property<int>("DataAnakId")
                        .HasColumnType("integer");

                    b.Property<string>("NamaAyah")
                        .HasColumnType("text");

                    b.Property<string>("NamaIbu")
                        .HasColumnType("text");

                    b.Property<string>("PekerjaanAyah")
                        .HasColumnType("text");

                    b.Property<string>("PekerjaanIbu")
                        .HasColumnType("text");

                    b.Property<float>("PenghasilanOrangTua")
                        .HasColumnType("real");

                    b.Property<string>("TandaTanganPath")
                        .HasColumnType("text");

                    b.Property<DateTime>("TanggalLahirAyah")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("TanggalLahirIbu")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("RiwayatOrangTuaId");

                    b.HasIndex("DataAnakId")
                        .IsUnique();

                    b.ToTable("RiwayatOrangTua");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.AppUserRole", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.AppRole", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bintangku.WebApi.Data.Entities.NakesUser", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.DataAnak", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.NakesUser", "NakesUser")
                        .WithMany("DataAnaks")
                        .HasForeignKey("NakesUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NakesUser");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiAnak", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.DataAnak", "DataAnak")
                        .WithOne("ImunisasiAnak")
                        .HasForeignKey("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiAnak", "DataAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiBCG", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiAnak", "ImunisasiAnak")
                        .WithOne("ImunisasiBCG")
                        .HasForeignKey("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiBCG", "ImunisasiAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImunisasiAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiCampak", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiAnak", "ImunisasiAnak")
                        .WithOne("ImunisasiCampak")
                        .HasForeignKey("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiCampak", "ImunisasiAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImunisasiAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiDTP", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiAnak", "ImunisasiAnak")
                        .WithOne("ImunisasiDTP")
                        .HasForeignKey("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiDTP", "ImunisasiAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImunisasiAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiDengue", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiAnak", "ImunisasiAnak")
                        .WithOne("ImunisasiDengue")
                        .HasForeignKey("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiDengue", "ImunisasiAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImunisasiAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiHPV", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiAnak", "ImunisasiAnak")
                        .WithOne("ImunisasiHPV")
                        .HasForeignKey("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiHPV", "ImunisasiAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImunisasiAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiHepatitisA", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiAnak", "ImunisasiAnak")
                        .WithOne("ImunisasiHepatitisA")
                        .HasForeignKey("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiHepatitisA", "ImunisasiAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImunisasiAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiHepatitisB", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiAnak", "ImunisasiAnak")
                        .WithOne("ImunisasiHepatitisB")
                        .HasForeignKey("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiHepatitisB", "ImunisasiAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImunisasiAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiHib", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiAnak", "ImunisasiAnak")
                        .WithOne("ImunisasiHib")
                        .HasForeignKey("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiHib", "ImunisasiAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImunisasiAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiInfluenza", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiAnak", "ImunisasiAnak")
                        .WithOne("ImunisasiInfluenza")
                        .HasForeignKey("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiInfluenza", "ImunisasiAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImunisasiAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiJapaneseEncephalitis", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiAnak", "ImunisasiAnak")
                        .WithOne("ImunisasiJapaneseEncephalitis")
                        .HasForeignKey("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiJapaneseEncephalitis", "ImunisasiAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImunisasiAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiMMR", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiAnak", "ImunisasiAnak")
                        .WithOne("ImunisasiMMR")
                        .HasForeignKey("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiMMR", "ImunisasiAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImunisasiAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiPCV", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiAnak", "ImunisasiAnak")
                        .WithOne("ImunisasiPCV")
                        .HasForeignKey("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiPCV", "ImunisasiAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImunisasiAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiPolio", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiAnak", "ImunisasiAnak")
                        .WithOne("ImunisasiPolio")
                        .HasForeignKey("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiPolio", "ImunisasiAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImunisasiAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiRotavirus", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiAnak", "ImunisasiAnak")
                        .WithOne("ImunisasiRotavirus")
                        .HasForeignKey("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiRotavirus", "ImunisasiAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImunisasiAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiTifoid", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiAnak", "ImunisasiAnak")
                        .WithOne("ImunisasiTifoid")
                        .HasForeignKey("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiTifoid", "ImunisasiAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImunisasiAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiVarisela", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiAnak", "ImunisasiAnak")
                        .WithOne("ImunisasiVarisela")
                        .HasForeignKey("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiVarisela", "ImunisasiAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ImunisasiAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.KesehatanAnak", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.DataAnak", "DataAnak")
                        .WithOne("KesehatanAnak")
                        .HasForeignKey("Bintangku.WebApi.Data.Entities.KesehatanAnak", "DataAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Pemeriksaan.PemeriksaanDayaDengar", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.KesehatanAnak", "KesehatanAnak")
                        .WithMany("PemeriksaanDayaDengars")
                        .HasForeignKey("KesehatanAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KesehatanAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Pemeriksaan.PemeriksaanDayaLihat", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.KesehatanAnak", "KesehatanAnak")
                        .WithMany("PemeriksaanDayaLihats")
                        .HasForeignKey("KesehatanAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KesehatanAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Pemeriksaan.PemeriksaanGpph", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.KesehatanAnak", "KesehatanAnak")
                        .WithMany("PemeriksaanGpphs")
                        .HasForeignKey("KesehatanAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KesehatanAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Pemeriksaan.PemeriksaanKmpe", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.KesehatanAnak", "KesehatanAnak")
                        .WithMany("PemeriksaanKmpes")
                        .HasForeignKey("KesehatanAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KesehatanAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Pemeriksaan.PemeriksaanKpsp", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.KesehatanAnak", "KesehatanAnak")
                        .WithMany("PemeriksaanKpsps")
                        .HasForeignKey("KesehatanAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KesehatanAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Pemeriksaan.PemeriksaanLingkarKepala", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.KesehatanAnak", "KesehatanAnak")
                        .WithMany("PemeriksaanLingkarKepalas")
                        .HasForeignKey("KesehatanAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KesehatanAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Pemeriksaan.PemeriksaanMchat", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.KesehatanAnak", "KesehatanAnak")
                        .WithMany("PemeriksaanMchats")
                        .HasForeignKey("KesehatanAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KesehatanAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Pemeriksaan.PemeriksaanStatusGiziBbTb", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.KesehatanAnak", "KesehatanAnak")
                        .WithMany("PemeriksaanStatusGiziBbTbs")
                        .HasForeignKey("KesehatanAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KesehatanAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Pemeriksaan.PemeriksaanStatusGiziImtU", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.KesehatanAnak", "KesehatanAnak")
                        .WithMany("PemeriksaanStatusGiziImtUs")
                        .HasForeignKey("KesehatanAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KesehatanAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Pemeriksaan.PemeriksaanStatusGiziIpTb", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.KesehatanAnak", "KesehatanAnak")
                        .WithMany("PemeriksaanStatusGiziIpTbs")
                        .HasForeignKey("KesehatanAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KesehatanAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Photo", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.NakesUser", "NakesUser")
                        .WithMany("Photos")
                        .HasForeignKey("NakesUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NakesUser");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.RiwayatKelahiran", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.DataAnak", "DataAnak")
                        .WithOne("RiwayatKelahiran")
                        .HasForeignKey("Bintangku.WebApi.Data.Entities.RiwayatKelahiran", "DataAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataAnak");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.RiwayatOrangTua", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.DataAnak", "DataAnak")
                        .WithOne("RiwayatOrangTua")
                        .HasForeignKey("Bintangku.WebApi.Data.Entities.RiwayatOrangTua", "DataAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataAnak");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.NakesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.NakesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("Bintangku.WebApi.Data.Entities.NakesUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.AppRole", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.DataAnak", b =>
                {
                    b.Navigation("ImunisasiAnak");

                    b.Navigation("KesehatanAnak");

                    b.Navigation("RiwayatKelahiran");

                    b.Navigation("RiwayatOrangTua");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.Imunisasi.ImunisasiAnak", b =>
                {
                    b.Navigation("ImunisasiBCG");

                    b.Navigation("ImunisasiCampak");

                    b.Navigation("ImunisasiDengue");

                    b.Navigation("ImunisasiDTP");

                    b.Navigation("ImunisasiHepatitisA");

                    b.Navigation("ImunisasiHepatitisB");

                    b.Navigation("ImunisasiHib");

                    b.Navigation("ImunisasiHPV");

                    b.Navigation("ImunisasiInfluenza");

                    b.Navigation("ImunisasiJapaneseEncephalitis");

                    b.Navigation("ImunisasiMMR");

                    b.Navigation("ImunisasiPCV");

                    b.Navigation("ImunisasiPolio");

                    b.Navigation("ImunisasiRotavirus");

                    b.Navigation("ImunisasiTifoid");

                    b.Navigation("ImunisasiVarisela");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.KesehatanAnak", b =>
                {
                    b.Navigation("PemeriksaanDayaDengars");

                    b.Navigation("PemeriksaanDayaLihats");

                    b.Navigation("PemeriksaanGpphs");

                    b.Navigation("PemeriksaanKmpes");

                    b.Navigation("PemeriksaanKpsps");

                    b.Navigation("PemeriksaanLingkarKepalas");

                    b.Navigation("PemeriksaanMchats");

                    b.Navigation("PemeriksaanStatusGiziBbTbs");

                    b.Navigation("PemeriksaanStatusGiziImtUs");

                    b.Navigation("PemeriksaanStatusGiziIpTbs");
                });

            modelBuilder.Entity("Bintangku.WebApi.Data.Entities.NakesUser", b =>
                {
                    b.Navigation("DataAnaks");

                    b.Navigation("Photos");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
