// <auto-generated />
using System;
using Bintangku.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Bintangku.Data.Migrations
{
    [DbContext(typeof(ApplicationDataContext))]
    [Migration("20210220143129_RefactorDataBase")]
    partial class RefactorDataBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Bintangku.Data.Entities.DataAnak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alamat")
                        .HasColumnType("TEXT");

                    b.Property<byte>("AnggotaRumahTangga")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApgarScore")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("BeratBadan")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JenisKelamin")
                        .HasColumnType("TEXT");

                    b.Property<byte>("JumlahSaudara")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KelahiranDibantuOleh")
                        .HasColumnType("TEXT");

                    b.Property<string>("Kontak")
                        .HasColumnType("TEXT");

                    b.Property<string>("LainLain")
                        .HasColumnType("TEXT");

                    b.Property<int>("NIK")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NakesUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NamaAyah")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaIbu")
                        .HasColumnType("TEXT");

                    b.Property<string>("NamaLengkap")
                        .HasColumnType("TEXT");

                    b.Property<int>("PanjangLahir")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PekerjaanOrangTua")
                        .HasColumnType("TEXT");

                    b.Property<float>("PenghasilanOranTua")
                        .HasColumnType("REAL");

                    b.Property<string>("TandaTanganOrangTua")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TanggalLahir")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NakesUserId");

                    b.ToTable("DataAnaks");
                });

            modelBuilder.Entity("Bintangku.Data.Entities.NakesUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastActive")
                        .HasColumnType("TEXT");

                    b.Property<long>("NoStrTenagaKesehatan")
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("BLOB");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("TempatPelayanan")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NakesUsers");
                });

            modelBuilder.Entity("Bintangku.Data.Entities.Photo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMain")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NakesUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NakesUserId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("Bintangku.Data.Entities.PhotoAnak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataAnakId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMain")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DataAnakId");

                    b.ToTable("PhotoAnak");
                });

            modelBuilder.Entity("Bintangku.Data.Entities.DataAnak", b =>
                {
                    b.HasOne("Bintangku.Data.Entities.NakesUser", "NakesUser")
                        .WithMany("DataAnaks")
                        .HasForeignKey("NakesUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NakesUser");
                });

            modelBuilder.Entity("Bintangku.Data.Entities.Photo", b =>
                {
                    b.HasOne("Bintangku.Data.Entities.NakesUser", "NakesUser")
                        .WithMany("Photos")
                        .HasForeignKey("NakesUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NakesUser");
                });

            modelBuilder.Entity("Bintangku.Data.Entities.PhotoAnak", b =>
                {
                    b.HasOne("Bintangku.Data.Entities.DataAnak", "DataAnak")
                        .WithMany("PhotoAnaks")
                        .HasForeignKey("DataAnakId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DataAnak");
                });

            modelBuilder.Entity("Bintangku.Data.Entities.DataAnak", b =>
                {
                    b.Navigation("PhotoAnaks");
                });

            modelBuilder.Entity("Bintangku.Data.Entities.NakesUser", b =>
                {
                    b.Navigation("DataAnaks");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
